# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWrG0CnLHsGAmDQsL-73Nk3roJW-1LuT
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import pytz

# Function to check if the current time is within the valid window (4 PM to 6 PM IST)
def is_valid_time():
    # Set timezone to IST
    ist = pytz.timezone('Asia/Kolkata')
    current_time = datetime.now(ist)
    current_hour = current_time.hour
    return 16 <= current_hour < 18  # 4 PM to 6 PM IST

# Function to create the violin plot
def plot_violin_plot(df):
    # Filter data based on conditions
    df_filtered = df[df['avg_rating'] >= 4.0]  # Filter apps with rating >= 4.0
    df_filtered = df_filtered[df_filtered['review_count'] >= 10]  # Exclude apps with fewer than 10 reviews
    df_filtered = df_filtered[df_filtered['app_name'].str.contains('C', case=False)]  # Filter apps with 'C' in the name

    # Group by category and count apps in each category
    category_counts = df_filtered.groupby('category').size()
    valid_categories = category_counts[category_counts > 50].index  # Filter categories with more than 50 apps

    df_filtered = df_filtered[df_filtered['category'].isin(valid_categories)]  # Keep only valid categories

    # Plotting the violin plot
    plt.figure(figsize=(12, 6))
    sns.violinplot(x='category', y='avg_rating', data=df_filtered, inner='quart', palette='muted')
    plt.xticks(rotation=45, ha='right')
    plt.title('Distribution of Ratings for Categories with More than 50 Apps and "C" in the Name')
    plt.xlabel('App Category')
    plt.ylabel('Average Rating')
    plt.tight_layout()
    plt.show()

# Main function to check time and plot the graph if it's valid
def main():
    if is_valid_time():
        # Assuming 'apps_data' is the DataFrame already loaded with the data
        plot_violin_plot(apps_data)  # Replace 'apps_data' with your actual data frame
    else:
        print("The graph is only available between 4 PM and 6 PM IST.")

# Example: Sample data (you need to replace this with your actual dataset)
apps_data = pd.DataFrame({
    'app_name': ['CoolApp1', 'ClassicGame', 'CandyCrush', 'CleverApp', 'CreativeGame', 'AppCool', 'Cinemagic', 'Calculator'],
    'avg_rating': [4.5, 3.8, 4.2, 4.7, 3.9, 4.6, 4.1, 4.3],
    'review_count': [200, 100, 500, 50, 20, 200, 700, 10],
    'category': ['Game', 'Game', 'Game', 'Utility', 'Game', 'Utility', 'Entertainment', 'Utility']
})

# Run the main function to plot the chart or print message if out of time
main()